// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aypvwqzfevthnqzhfjyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5cHZ3cXpmZXZ0aG5xemhmanlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNDQ3NzUsImV4cCI6MjA2ODgyMDc3NX0.SkIrgXq7EU5mrc7BXORCcklKm70sT83lkgRDMsLKrts";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});